dist: trusty
sudo: true

services:
  - docker

language: node_js
node_js:
  - 14

os:
  - linux

branches:
  only:
    - master

before_install:
  - bash install_kubectl.sh

script:
  - yarn build
  - docker build -t moondropx/naberius .

after_success:
  - bash docker_push.sh
  - bash kube_deploy.sh
