import { Config } from './config.model';

export const Consts: Partial<Config> = {
  ASSETS_BASE_URL: 'http://assets.millennium-war.net',
  HARLEM_TEXT_R_DIR: 'HarlemTextR',
  HARLEM_TEXT_A_DIR: 'HarlemTextA',
  CACHE_DIR: 'cache',
  DATA_DIR: 'data',
  MISSION_DIR: 'mission',
  QUEST_NAME_TEXT_DIR: 'questNameText',
  MESSAGE_TEXT_DIR: 'messageText',
  ICO_DIR: 'ico',
  EVENT_ARC_DIR: 'eventArc',
  PLAYER_DOT_DIR: 'playerDot',
  ENEMY_DOT_DIR: 'enemyDot',
  BATTLE_TALK_EVENT_DIR: 'battleTalkEvent',
  MAP_DIR: 'map',
  ENEMY_DIR: 'enemy',
  POSTER_DIR: 'poster',
  BANNER_DIR: 'banner',
  PORT: '4000',
  MONGO_HOST: 'localhost',
  MONGO_PORT: '27017',
  MONGO_DATABASE: 'aigis',
};
